version: '3.5'

services:

  perfstat:
    build: .
    environment:
      - RUN_TESTS=false
    volumes:
      - ./:/app
      - ./dist:/dist
      # - /proc:/host/proc:ro
      # - /sys:/host/sys:ro
      # - /:/rootfs:ro
      # - /etc/hostname:/etc/hostname
    privileged: true
    # stdin_open: true
    # tty: true
    ports: 
      - 8880:8880
    # command: sleep 99999

