version: '3.5'

services:

  perfstat:
    build: .
    environment:
      - RUN_TESTS=false
    volumes:
      - ./:/app
      - ./dist:/dist
    privileged: true
    stdin_open: true
    tty: true
    command: sleep 99999

